########################################
##PBS Controls       
########################################
#PBS -S /bin/bash
#PBS -l nodes=1:ppn=6
#PBS -l walltime=16:00:00
#PBS -V
#PBS -W group_list=liz.suehr
#PBS -N shear_rod2_2_10

########################################
#===================================================================#
# Load modules and move to current directory
#===================================================================#

module load /home/liz.suehr/modules/openmpi/mvapich23-x86_64
module load /home/liz.suehr/modules/liggghts/3.0
cd $PBS_O_WORKDIR

#===================================================================#
# Run simulation
#===================================================================#

mpiexec -np 6 lmp_auto < in.shear.rod2_2_10 > stdout_shear_2_10

